esphome:
  name: banya
  friendly_name: Banya

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "pUevChdRsaxB64BL2HQgdHtKZ+sx/mOjt73i1mv36UI="

ota:
  - platform: esphome
    password: "cfe881ff8d57e3f8b6f8e5c09c0d7fa7"

wifi:
  #
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: "BSMSP+"
      password: !secret wifi_password
    
  ap:
    ssid: "Banya"
    password: "banya374"

captive_portal:

web_server:
    port: 80
    version: 2
    local: true

i2c:
   - id: bus_a
     sda: 22
     scl: 23
     scan: true

esp32_ble_tracker:
 
sensor:
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
    id: wifi_signal_sensor

  - platform: aht10
    i2c_id: bus_a
    temperature:
      name: "In Temperature"
      id: in_temp
    humidity:
      name: "In Humidity"
      id: in_hum
    update_interval: 60s

  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: pvvx_mithermometer
    mac_address: A4:C1:38:9C:77:9E
    temperature:
      name: "Sensor tubes Temperature"
    battery_level:
      name: "Sensor tubes Battery-Level"
    battery_voltage:
      name: "Sensor tubes Battery-Voltage"
    signal_strength:
      name: "Sensor tubes Signal"


button:
  - platform: restart
    name: "Restart"

