esphome:
  name: ble-tracker
  friendly_name: ble-tracker

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "aO+/zGrzpSJ1DbSukBHc6uxd4ipzCJNP7atGSONU97A="

ota:
  password: "960b9d1043b93a5a9dc1fed573ab86bf"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ble-Tracker Fallback Hotspot"
    password: "TtiGXraZ5r1f"

captive_portal:

esp32_ble_tracker:

ble_client:
  - mac_address: 70:28:45:69:25:49
    id: oclean_x_pro
  - mac_address: F1:CD:D8:62:81:FA
    id: mi_band_6

sensor:
  - platform: uptime
    name: "Uptime Sensor"
  
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s


  - platform: ble_client
    type: characteristic
    ble_client_id: oclean_x_pro
    name: "Oclean X Pro battery level"
    service_uuid: '180f'
    characteristic_uuid: '2a19'
    icon: 'mdi:battery'
    unit_of_measurement: '%'
    update_interval: 12h

  - platform: ble_client
    type: characteristic
    ble_client_id: mi_band_6
    name: "Mi Band 6 battery level"
    service_uuid: '180f'
    characteristic_uuid: '2a19'
    icon: 'mdi:battery'
    unit_of_measurement: '%'
    update_interval: 12h
  



    
