esphome:
  name: boiler
  friendly_name: Boiler

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MBKzDFHCNtE7arzwgBn6q6PgCHGyQPUIKUGU120OuyM="

ota:
  - platform: esphome
    password: "23d9c336142b5ed88fa408960a499929"

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_password 


  ap:
    ssid: "boiler"
    password: "bstemp374"

captive_portal:

web_server:
    port: 80
    version: 2
    local: true

one_wire:
  - platform: gpio
    pin: 18

sensor:

  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
    id: wifi_signal_sensor

  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: dallas_temp
    address: 0xd9113d8109646128
    name: "Sensor 1"

  - platform: dallas_temp
    address: 0x4a895e8309646128
    name: "Sensor 2"

  - platform: dallas_temp
    address: 0x1167758109646128
    name: "Sensor 3" 
    