esphome:
  name: bs-temp
  friendly_name: BS-temp

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s
  encryption:
    key: "31vX1V+SOgZlRjG45keEDnjptvT7B8hCWsduq6TRVQg="
    

ota:
  password: "c723398e4637dbf4f0b4a88885ede3be"

wifi:
  networks:
    - ssid: !secret wifi_ssid 
      password: !secret wifi_password 
    - ssid: !secret wifi_ssid_bs 
      password: !secret wifi_password_bs

  ap:
    ssid: "BS-Temp"
    password: "bstemp374"

captive_portal:

web_server:
    port: 80
    version: 2
    local: true

time: 
  - platform: sntp
    servers:
       - 0.pool.ntp.org
       - 1.pool.ntp.org

i2c:
  sda: 22
  scl: 23
  scan: true
  id: bus_a

sensor:
  - platform: uptime
    name: Uptime Sensor

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

 # - platform: dht
 #   pin: 18
 #   temperature:
 #     name: "Out Temperature"
 #     id: out_temp
 #   humidity:
 #     name: "Out Humidity"
 #     id: out_hum
 #   update_interval: 60s

  - platform: aht10
    temperature:
      name: "In Temperature"
      id: in_temp
    humidity:
      name: "In Humidity"
      id: in_hum
    update_interval: 60s

button:
  - platform: restart
    name: "Restart"

switch:
  - platform: gpio
    pin: 2
    name: "Led"

binary_sensor:
  - platform: gpio
    pin: 0
    name: "Pin 0 button"

