esphome:
  name: diploma-domik
  friendly_name: Diploma-Domik

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "3a7Q1tDlKBET3iXNAkYRJTVcQCYJ5aAmXjNBlThJ6G4="

ota:
  password: "d83a794d94fef5c6a2369f09a0819c65"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Diploma-Domik Fallback Hotspot"
    password: "M4en5974sN71"

captive_portal:

web_server:
    port: 80
    version: 2
    local: true


sensor:

  - platform: uptime
    name: "Uptime"
    update_interval: 10s

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 10s
    
  - platform: dht
    pin: 19
    temperature:
      name: "DHT Temperature"
    humidity:
      name: "DHT Humidity"
    update_interval: 1s

  - platform: adc
    pin: 35
    name: "Brightness"
    update_interval: 1s
    id: brightness

binary_sensor:
  - platform: gpio
    pin: 25
    name: "Door"
    device_class: window  

switch:
  - platform: gpio
    pin: 2
    name: "LEDS"

    