esphome:
  name: ds18b20-temperture-server
  friendly_name: Ds18b20 temperture server

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Utahrq953kMpqBNRWF2LXaoj4exFPLK/tP5PFCG2WQ0="

ota:
  - platform: esphome
    password: "a69c937c815c1caa0cab55120cdfca7a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ds18B20-Temperture-Server"
    password: "Ll0fk1orwkp7"

captive_portal:

one_wire:
  - platform: gpio
    pin: 2

sensor:

  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
    id: wifi_signal_sensor

  - platform: dallas_temp
    address: 0xaa1684570a646128
    name: "Sensor"

switch:
  - platform: gpio
    pin: D5
    name: led

    