esphome:
  name: rgb-dog
  friendly_name: rgb-dog

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "fv885msqv0woIDV7oHQ15i7GmgLJ5amFqjUMlSRjzh4="

ota:
  password: "2551806e96c2d0a5af718fc3b25a2cec"

wifi:
  networks:
    - ssid: !secret wifi_ssid 
      password: !secret wifi_password 
    - ssid: !secret wifi_ssid_bs 
      password: !secret wifi_password_bs
    
captive_portal:

sensor:
  - platform: uptime
    name: "Uptime Sensor"
  
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
  
binary_sensor:
  - platform: gpio
    name: "Button"
    pin:
      number: 0
      inverted: false
    on_click:
      then:
        - light.toggle: leds
    on_double_click:
      then:
        - light.turn_on: 
            id: leds
            brightness: 35%
            #red: 100%
            #green: 100%
            #blue: 100%

output:
  - platform: esp8266_pwm
    pin: 16
    frequency: 20000 Hz
    id: pwm_output_1

  - platform: esp8266_pwm
    pin: 14
    frequency: 20000 Hz
    id: pwm_output_2

  - platform: esp8266_pwm
    pin: 12
    frequency: 20000 Hz
    id: pwm_output_3

light:
  - platform: rgb
    name: "Leds"
    red: pwm_output_1
    green: pwm_output_2
    blue: pwm_output_3
    id: leds
    
